main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('accounts/signup/', views.signup, name='signup'),
    path('recipes/', views.recipes_index, name='index'),
    path('recipes/my/', views.recipes_myindex, name='myindex'),
    path('recipes/create/', views.RecipeCreate.as_view(), name='recipe_create'),
    path('recipes/<int:recipe_id>/', views.recipes_detail, name='detail'),
    path('recipes/<int:pk>/update/', views.RecipeUpdate.as_view(), name='recipe_update'),
    path('recipes/<int:pk>/delete/', views.RecipeDelete.as_view(), name='recipe_delete'),
    path('recipes/<int:recipe_id>/add_comment/', views.add_comment, name='add_comment'),
    path('recipes/<int:pk>/comment_delete', views.CommentDelete.as_view(), name='comment_delete'),
    path('recipes/<int:recipe_id>/add_tiptrick/', views.add_tiptrick, name='add_tiptrick'),
    path('recipes/<int:pk>/tiptrick_delete', views.TipTrickDelete.as_view(), name='tiptrick_delete'),
    path('recipes/<int:recipe_id>/add_photo/', views.add_photo, name='add_photo'),

]

recipeapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.core.validators import MaxValueValidator, MinValueValidator
from datetime import date

# Create your models here.
CATEGORIES = (
    ('VT', 'Vegetarian'),
    ('VE', 'Vegan'),
    ('B', 'Breakfast'),
    ('L', 'Lunch'),
    ('D', 'Dinner'),
)


class Recipe(models.Model):
    title = models.CharField(max_length=100)
    chef = models.ForeignKey(User, on_delete=models.CASCADE)
    servings = models.IntegerField()
    preptime = models.IntegerField()
    cookingtime = models.IntegerField()
    category = models.CharField(
        max_length=2,
        choices=CATEGORIES,
        default=CATEGORIES[0][0]
    )
    method = models.TextField()
    ingredients = models.TextField()

    def __str__(self):
        return f'{self.title} ({self.id})'

    def get_absolute_url(self):
        return reverse('home')

    class Meta:
        ordering = ['title']

class Comment(models.Model):
    chef = models.ForeignKey(User, on_delete=models.CASCADE)
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    content = models.TextField(max_length=500)
    created = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.content

    class Meta:
        ordering = ['-created']


class TipTrick(models.Model):
    chef = models.ForeignKey(User, on_delete=models.CASCADE)
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    content = models.TextField(max_length=500)
    created = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.content

    class Meta:
        ordering = ['-created']


class Photo(models.Model):
    url = models.CharField(max_length=200)
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for recipe_id: {self.recipe_id} @{self.url}"

main_app/forms.py
from django.forms import ModelForm
from .models import Comment, TipTrick

class CommentForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    class Meta:
        model = Comment
        fields = ['content']

class TipTrickForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    class Meta:
        model = TipTrick
        fields = ['content']

main_app/views.py
import os
import uuid
import boto3

from random import choice

from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from .models import Recipe, Comment, TipTrick, Photo
from .forms import CommentForm, TipTrickForm

# Create your views here.
def home(request):
  recipeIds = Recipe.objects.values_list('id', flat=True)
  randomId = choice(recipeIds)
  recipe = Recipe.objects.get(id=randomId)
  return render(request, 'home.html', { 'recipe': recipe })


@login_required
def recipes_index(request):
  recipes = Recipe.objects.all()
  return render(request, 'recipes/index.html', { 'recipes': recipes })    


@login_required
def recipes_myindex(request):
  recipes = Recipe.objects.filter(chef=request.user)
  return render(request,'recipes/myindex.html', { 'recipes': recipes })


def recipes_detail(request, recipe_id):
  recipe = Recipe.objects.get(id=recipe_id)
  comment_form = CommentForm()
  tiptrick_form = TipTrickForm()
  return render(request, 'recipes/detail.html', {
    'recipe': recipe,
    'comment_form': comment_form,
    'tiptrick_form': tiptrick_form,
  })


@login_required
def add_comment(request, recipe_id):
  form = CommentForm(request.POST)
  if form.is_valid():
    new_comment = form.save(commit=False)
    new_comment.recipe_id = recipe_id
    new_comment.chef_id = request.user.id
    new_comment.save()
  return redirect('detail', recipe_id=recipe_id)


@login_required
def add_tiptrick(request, recipe_id):
  form = TipTrickForm(request.POST)
  if form.is_valid():
    new_tiptrick = form.save(commit=False)
    new_tiptrick.recipe_id = recipe_id
    new_tiptrick.chef_id = request.user.id
    new_tiptrick.save()
  return redirect('detail', recipe_id=recipe_id)


def signup(request):
  error_message = ''
  if request.method == 'POST':
    form = UserCreationForm(request.POST)
    if form.is_valid():
      user = form.save()
      login(request, user)
      return redirect('index')
    else:
      error_message = 'Invalid sign up - try again'
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)


class RecipeCreate(CreateView, LoginRequiredMixin):
  model = Recipe
  fields = ['title', 'servings', 'preptime', 'cookingtime', 'category', 'ingredients', 'method']
  def get_success_url(self):
    return f"/recipes/{self.object.id}"

  def form_valid(self, form):
    form.instance.chef = self.request.user
    return super().form_valid(form)


class RecipeUpdate(UpdateView, LoginRequiredMixin):
  model = Recipe
  fields = ['title', 'servings', 'preptime', 'cookingtime', 'category', 'ingredients', 'method']
  def get_success_url(self):
    return f"/recipes/{self.object.id}"


class RecipeDelete(DeleteView, LoginRequiredMixin):
  model = Recipe
  success_url = '/recipes/'


class CommentDelete(DeleteView, LoginRequiredMixin):
  model = Comment
  def get_success_url(self):
    return f"/recipes/{self.object.recipe.id}"


class TipTrickDelete(DeleteView, LoginRequiredMixin):
  model = TipTrick
  def get_success_url(self):
    return f"/recipes/{self.object.recipe.id}"


def random(self):
  return self.objects.order_by('?').values('cookingtime','title','chef_id').first()

@login_required
def add_photo(request, recipe_id):
  # photo-file will be the "name" attribute on the <input type="file">
  photo_file = request.FILES.get('photo-file', None)
  if photo_file:
    s3 = boto3.client('s3')
    # need a unique "key" for S3 / needs image file extension too
    key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
    # just in case something goes wrong
    try:
      bucket = os.environ['S3_BUCKET']
      s3.upload_fileobj(photo_file, bucket, key)
      # build the full url string
      url = f"{os.environ['S3_BASE_URL']}{bucket}/{key}"
      # we can assign to recipe_id or recipe (if you have a recipe object)
      Photo.objects.create(url=url, recipe_id=recipe_id)
    except Exception as e:
      print('An error occurred uploading file to S3')
      print(e)
  return redirect('detail', recipe_id=recipe_id)

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="shortcut icon" type="image" href="https://i.imgur.com/McOVznj.png" />
    <title>Simply Recipes</title>
</head>
<body>
    <header>
        <img src="{% static 'images/logo.png' %}" alt="Simply Recipes Logo" class="banner-logo">
        <nav>
            <ul>
                <li><a href="{% url 'home' %}">Home</a></li> <!--SHOWS SINGLE RANDOM RECIPE AND ENCOURAGES SIGN UP-->
                {% if user.is_authenticated %}
                    <li><a href="{% url 'index' %}">View All Recipes</a></li> <!--GOES HERE ONCE THEY LOG IN-->
                    <li><a href="{% url 'myindex' %}">My Recipes</a></li>
                    <li><a href="{% url 'recipe_create' %}">Add New Recipe</a></li>
                    <li><a href="{% url 'logout' %}">Log Out</a></li>
                {% else %}
                    <li><a href="{% url 'signup' %}">Sign Up</a></li>
                    <li><a href="{% url 'login' %}">Log In</a></li>
            {% endif %}
            </ul>
        </nav>
    </header>
    <main>
        {% block content %}
        {% endblock %}
    </main>
    <footer>
        All Rights Reserved &copy; 2022 Simply Recipes
    </footer>    
</body>
</html>

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<div class="home">
    <br>
    <h1>Welcome to Simply Recipes!</h1>
    <br>
    <h2>Do you enjoy cooking but never know what to cook? You've come to the right place!</h2>
    <h2>With Simply Recipes you will be able to create new recipes and view submissions by other users all in one place!</h2>
    <h2>Here is a sample of what Simply Recipes has to offer:</h2>
    <br>
    <div class="homepage-recipe">
        <a href="{% url 'detail' recipe.id %}" class="recipe-card" style="background-image: url('{{ recipe.photo_set.all.0.url }}')">
            <div class="recipe-details">
                <h2>{{ recipe.title }}</h2>
                <h3>Total Time: {{ recipe.preptime | add:recipe.cookingtime }} minutes</h3>
            </div>
        </a>
    </div>
    <br>
    {% if request.user.is_authenticated %}
        <h2></h2>
    {% else %}
        <h2>Please <a href="{% url 'signup' %}">Sign Up</a> or <a href="{% url 'login' %}">Log In</a> to access this feature and more!</h2>
    {% endif %}
</div>



{% endblock %}

main_app/templates/main_app/comment_confirm_delete.html
{% extends 'base.html' %}
{% block content %}

<div class="confirm-delete">

  <h1>Delete Comment</h1>

  <h2>Are you sure you want to delete your comment ({{ object.content }})?</h2>

  <br>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' object.recipe.id %}">Cancel</a>
  </form>

</div>
{% endblock %}

main_app/templates/main_app/recipe_confirm_delete.html
{% extends 'base.html' %}
{% block content %}

<div class="confirm-delete">
  <h1>Delete Recipe</h1>

  <h2>Are you sure you want to delete {{ recipe.title }}?</h2>

  <br>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' recipe.id %}">Cancel</a>
  </form>

</div>
{% endblock %}

main_app/templates/main_app/recipe_form.html
{% extends 'base.html' %}
{% block content %}


{% if object %}
<div class="recipe-form">
  <h1>Edit {{ object.title }}</h1>
  <form action="" method="POST" id="recipe-form">
    {% csrf_token %}
    <table>
        <tr>
          <td class="form-title">Title:</td>
          <td><input name="title" type="text" value="{{ object.title }}" required></td>
        </tr>
        <tr>
          <td class="form-title">Servings:</td>
          <td><input name="servings" type="number" value="{{ object.servings }}" ></td>
        </tr>
        <tr>
          <td class="form-title">Prep Time:</td>
          <td><input name="preptime" type="number" value="{{ object.preptime }}" ></td>
        </tr>
        <tr>
          <td class="form-title">Cooking Time:</td>
          <td><input name="cookingtime" type="number" value="{{ object.cookingtime }}" ></td>
        </tr>
        <tr>
          <td class="form-title">Category:</td>
          <td>
            <select name="category" id="category">
              <option value="{{ object.category }}" selected>{{ object.get_category_display }}</option>
              <option value="VT">Vegetarian</option>
              <option value="VE">Vegan</option>
              <option value="B">Breakfast</option>
              <option value="L">Lunch</option>
              <option value="D">Dinner</option>
            </select>
          </td>
        </tr>
        <tr>
          <td class="form-title">Ingredients:</td>
          <td><textarea name="ingredients" id="" cols="20" rows="10" placeholder="Please add your ingredients, and make a new line for each ingredient.">{{ object.ingredients }}</textarea></td>
        </tr>
        <tr>
          <td class="form-title">Method:</td>
          <td><textarea name="method" id="" cols="20" rows="10" required>{{ object.method }}</textarea></td>
        </tr>
    </table>
    <input type="submit" value="Update Recipe" class="btn">
  </form>
</div>


{% else %}
<div class="recipe-form">
  <h1>Add Recipe</h1>
  <form action="" method="POST" id="recipe-form">
      {% csrf_token %}
      <table>
          <tr>
            <td class="form-title">Title:</td>
            <td><input name="title" type="text" required></td>
          </tr>
          <tr>
            <td class="form-title">Servings:</td>
            <td><input name="servings" type="number" required></td>
          </tr>
          <tr>
            <td class="form-title">Prep Time:</td>
            <td><input name="preptime" type="number" required></td>
          </tr>
          <tr>
            <td class="form-title">Cooking Time:</td>
            <td><input name="cookingtime" type="number" required></td>
          </tr>
          <tr>
            <td class="form-title">Category:</td>
            <td>
              <select name="category" required>
                <option value="" disabled selected>Select a Category</option>
                <option value="VT">Vegetarian</option>
                <option value="VE">Vegan</option>
                <option value="B">Vegetarian</option>
                <option value="L">Lunch</option>
                <option value="D">Dinner</option>
              </select>
            </td>
          </tr>
          <tr>
            <td class="form-title">Ingredients:</td>
            <td><textarea name="ingredients" id="" cols="20" rows="10" placeholder="Please add your ingredients, and make a new line for each ingredient." required></textarea></td>
          </tr>
          <tr>
            <td class="form-title">Method:</td>
            <td><textarea name="method" id="" cols="20" rows="10" placeholder="Please add your steps, and make a new line for each step." required></textarea></td>
          </tr>
      </table>
      <input type="submit" value="Add Recipe" class="btn">
  </form>
</div>
{% endif %}

{% endblock %}

main_app/templates/main_app/tiptrick_confirm_delete.html
{% extends 'base.html' %}
{% block content %}

<div class="confirm-delete">

  <h1>Delete Tip / Trick</h1>

  <h2>Are you sure you want to delete your tips or tricks ({{ object.content }})?</h2>

  <br>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' object.recipe.id %}">Cancel</a>
  </form>

</div>
{% endblock %}

main_app/templates/recipes/detail.html
{% extends 'base.html' %}
{% block content %}

<div class="detail-page">
    <div class="title">
        <h1>{{ recipe.title }}</h1>
        <h5>Chef: {{ recipe.chef }}</h5>
    </div>

    <div class="photo">
        {% for photo in recipe.photo_set.all %}
        <img src="{{photo.url}}" class="detail-img">
        {% empty %}
        <div>No Photos Uploaded</div>
        {% endfor %}
    </div>

    <div class="recipe-all">
        <h5 class="servings">Servings: {{ recipe.servings }}</h5>
        <h5 class="time">Prep Time: {{ recipe.preptime}} minutes</h5>
        <h5 class="time">Cooking Time: {{ recipe.cookingtime }} minutes</h5>
        <h5 class="category">Category: {{ recipe.get_category_display }}</h5>
        <div class="method-ingred">
            <h5 class="heading">Method:</h5>
            <h5 class="heading">Ingredients:</h5>
            <h5 class="contentheader method">{{ recipe.method|linebreaks }}</h5>
            <h5 class="contentheader ingredients">{{ recipe.ingredients|linebreaks }}</h5>
        </div>
    </div>

    {% if recipe.chef == request.user %}
        <div class="add-photo">
            <form action="{% url 'add_photo' recipe.id %}" enctype="multipart/form-data" method="POST" alt="Recipe Photo">
                {% csrf_token %}
                <input type="file" name="photo-file" >
                <br><br>
                <input type="submit" value="Upload Photo" class="btn">
            </form>
        </div>

    <div class="edit-delete">
        <a href="{% url 'recipe_update' recipe.id %}"><button class="btn">Edit</button></a>
        <a href="{% url 'recipe_delete' recipe.id %}"><button class="btn">Delete</button></a>
    </div>
    {% endif%}

    <div class="all-comment">
        
            <div class="add-comment">
                
                    <form action="{% url 'add_comment' recipe.id %}" method="POST" class="tiptrick-form">
                        {% csrf_token %}
                        <p class="table-headers">Comments</p>
                        {% if request.user.is_authenticated %}
                        {{ comment_form.as_p }}
                        <input type="submit" value="Post Comment" class="btn post-tiptrick">
                        {% else %}
                        {% endif %}
                    </form> 

            </div>

        
        <div class="view-comment">
            <table class="content-table">
                {% for comment in recipe.comment_set.all %}
                    <tr>
                        <td class="table-chef">{{ comment.chef }}</td>
                        <td class="table-date">{{ comment.created|date:"M d, Y" }}</td>
                        {% if comment.chef.id == request.user.id %}
                        <td rowspan="2" class="delete-cell"><a href="{% url 'comment_delete' comment.id %}"><button class="btn delete-content">X</button></a></td>
                        {% endif %}
                    </tr>
                    <tr>
                        <td colspan="2">{{ comment.content|linebreaks }}</td>
                    </tr>
                {% empty %}
                    <h2>There are no comments yet</h2>
                {% endfor %}
            </table>
        </div>
    </div>


    <div class="all-tiptrick">
        <div class="add-tiptrick">
            <form action="{% url 'add_tiptrick' recipe.id %}" method="POST" class="tiptrick-form">
                {% csrf_token %}
                <p class="table-headers">Tips and Tricks</p>
                {% if request.user.is_authenticated %}
                {{ comment_form.as_p }}
                <input type="submit" value="Post Tips or Tricks" class="btn post-tiptrick">
                {% else %}
                {% endif %}
            </form>
        </div>
        <div class="view-comment">
            <table class="content-table">
                {% for tiptrick in recipe.tiptrick_set.all %}
                    <tr>
                        <td class="table-chef">{{ tiptrick.chef }}</td>
                        <td class="table-date">{{ tiptrick.created|date:"M d, Y" }}</td>
                        {% if tiptrick.chef.id == request.user.id %}
                        <td rowspan="2" class="delete-cell"><a href="{% url 'tiptrick_delete' tiptrick.id %}"><button class="btn delete-content">X</button></a></td>
                        {% endif %}
                    </tr>
                    <tr>
                        <td colspan="2">{{ tiptrick.content|linebreaks }}</td>
                    </tr>
                {% empty %}
                    <h2>There are no tips or tricks yet</h2>
                {% endfor %}
            </table>
        </div>
    </div>
</div>

{% endblock %}

main_app/templates/recipes/index.html
{% extends 'base.html' %}
{% block content %}

<h1>All Recipes</h1>

<div class="all-recipes">
    {% for recipe in recipes %}
        <a href="{% url 'detail' recipe.id %}" class="recipe-card" style="background-image: url('{{ recipe.photo_set.all.0.url }}')">
            <div class="recipe-details">
                <h2>{{ recipe.title }}</h2>
                <h3>Total Time: {{ recipe.preptime | add:recipe.cookingtime }} minutes</h3>
            </div>
        </a>
    {% endfor %}
</div>
<br>
<br>

{% endblock %}

main_app/templates/recipes/myindex.html
{% extends 'base.html' %}
{% block content %}

<h1>My Recipes</h1>

<div class="all-recipes">
    {% for recipe in recipes %}
        <a href="{% url 'detail' recipe.id %}" class="recipe-card" style="background-image: url('{{ recipe.photo_set.all.0.url }}')">
            <div class="recipe-details">
                <h2>{{ recipe.title }}</h2>
                <h3>Total Time: {{ recipe.preptime | add:recipe.cookingtime }} minutes</h3>
            </div>
        </a>
    {% endfor %}
</div>
<br>
<br>

{% endblock %}